### PR TITLE
Add extensibleMatch filter support, fix multi-byte filters

### LINKED ISSUE #28: filter by memberOf + nested groups
Is the following search filter possible with this library? Didn't seem like it worked, based on my limited testing with a hacked up example_test.go.

```
memberOf:CN=Some-App-Group,OU=Groups,DC=example,DC=com
```

Also, is it possible to search nested group membership, similar to the following?

```
memberOf:1.2.840.113556.1.4.1941:=CN=Some-App-Group,OU=Groups,DC=example,DC=com
```

Apologies if this is obvious in the code -- I'm not a Go developer but need to add this functionality to an app that uses this library.

### LINKED ISSUE #39: filter failed with chinese language
Filter: "(&(objectclass=inetorgperson)(cn=中文))"

this filter will failed

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #28

* adds support for [extensible match](https://tools.ietf.org/search/rfc2254#section-3) sequence (both in CompileFilter and DecompileFilter)
* switched the filter parse to a simple state machine, rather than keying off whether the packet was nil, since attribute parsing could transition to extension matching rule or filter value
* simplified "nextRune" handling to check "currentRune" for performance, then do simple HasPrefix checks. Needed to check variable length prefixes like ":dn:=", ":dn:", etc.
* Fixed encoding of substring match strings and added tests.

Fixes #39

* In cases where we got non-escaped content in the condition, we were iterating on bytes, not runes
* Fixed incorrect multi-byte testcases, and verified byte output matches actual bytes for those characters

### CODE REVIEW

File: filter.go [hunk 1]
```diff
@@ -257,38 +398,49 @@ func compileFilter(filter string, pos int) (*ber.Packet, int, error) {
...
+			packet.AppendChild(ber.NewString(ber.ClassUniversal, ber.TypePrimitive, ber.TagOctetString, encodedString, "Condition"))
 		}
 
 		newPos += currentWidth
 		return packet, newPos, err
 	}
 }
+
+// Convert from "ABC\xx\xx\xx" form to literal bytes for transport
+func escapedStringToEncodedBytes(escapedString string) (string, error) {
```
Comment (liggitt) [inline filter.go]: refactored so that substring and extensible match filters can reuse this

**Comment by liggitt** [comment]
@johnweldon please take a look

**Comment by liggitt** [comment]
Tested against a live LDAP server with the following extensions:
```
    ( 1.3.6.1.4.1.1466.109.114.1 NAME 'caseExactIA5Match'
      SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )

    ( 1.3.6.1.4.1.1466.109.114.2 NAME 'caseIgnoreIA5Match'
      SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 )
```

Search filters were accepted as valid, and behavior indicated extension was passed successfully

```
// case-sensitive match, 1 result returned
(uid:1.3.6.1.4.1.1466.109.114.1:=myuid)

// no match, zero results returned
(uid:1.3.6.1.4.1.1466.109.114.1:=MYUID)

// case-insensitive match, 1 result returned
(uid:1.3.6.1.4.1.1466.109.114.2:=MYUID)
```

File: filter_test.go [hunk 2]
```diff
@@ -121,9 +133,45 @@ var testFilters = []compileTest{
 	},
 	compileTest{
 		filterStr:      `(&(objectclass=inetorgperson)(cn=中文))`,
```
Comment (liggitt) [inline filter_test.go]: in case you want to verify the old bytes were wrong, and the new bytes are right: http://play.golang.org/p/GeNmpuSEs7

File: filter.go [hunk 3]
```diff
@@ -257,38 +395,56 @@ func compileFilter(filter string, pos int) (*ber.Packet, int, error) {
...
-					}
-					if escByte, decodeErr := hexpac.DecodeString(condition[i+1 : i+3]); decodeErr != nil {
-						err = NewError(ErrorFilterCompile, errors.New("ldap: invalid characters for escape in filter"))
-						return packet, newPos, err
-					} else {
-						buffer.WriteByte(escByte[0])
-						i += 2 // +1 from end of loop, so 3 total for \xx.
-					}
-				} else {
-					buffer.WriteString(string(condition[i]))
```
Comment (liggitt) [inline filter.go]: this was the line causing multi-byte headaches... should have been write rune

**Comment by stevekuznetsov** [comment]
What behavior will this have for nested groups?

**Comment by liggitt** [comment]
It lets you tell the AD server you want it to flatten membership for you, rather than recursing yourself

File: filter.go (hunk 3 above)
Comment (johnweldon) [inline filter.go]: nice catch

**Comment by johnweldon** [comment]
LGTM, :shipit:
