### PR TITLE
Handle nil packets when getting LDAPResultCode

### LINKED ISSUE #58: nil pointer panic when StartTLS fails
Thanks for creating and sharing this library!

I'm reproducibly getting a nil pointer panic when StartTLS fails. I can reproduce using a free account on jumpcloud.com and trying to use StartTLS on port 686 (the TLS-enabled port). Of course, this isn't expected to work, but hopefully we can avoid a panic.

```
conn, err := ldap.Dial("tcp", "ldap.jumpcloud.com:686")
if err != nil {
  log.Fatal("Error opening connection")
  return;
}
conn.StartTLS(&tls.Config{InsecureSkipVerify: ldapConfig.ServerTLSInsecure, ServerName: serverName})
```

The last line there will panic and the stack trace takes us through:
https://github.com/go-ldap/ldap/blob/v2.2.1/conn.go#L182
https://github.com/go-ldap/ldap/blob/07a7330929b9ee80495c88a4439657d89c7dbd87/error.go#L102
where we get a nil pointer. It seems that `packet` or `Children` must be nil.

The panic does *not* occur when conn.Debug is set to true. When Debugging is enabled, we get the following output (our own logging intermingled with this package's).

```
2016/04/11 19:18:11 /connect/src/connect/auth/providers/ldap/client.go:129: (ldap) Dialing unencrypted LDAP connection: ldap.jumpcloud.com:636
2016/04/11 19:18:11 /connect/src/connect/auth/providers/ldap/client.go:139: (ldap) Using StartTLS on LDAP connection: ldap.jumpcloud.com:636
LDAP Request: (Universal, Constructed, Sequence and Sequence of) Len=29 "<nil>"
 MessageID: (Universal, Primitive, Integer) Len=1 "1"
 Start TLS: (Application, Constructed, 0x17) Len=24 "<nil>"
  TLS Extended Command: (Context, Primitive, 0x00) Len=22 "1.3.6.1.4.1.1466.20037"
2016/04/11 19:18:11 flags&startTLS = 1
2016/04/11 19:18:11 1: waiting for response
2016/04/11 19:18:11 Sending message 1
2016/04/11 19:18:11 reader error: unexpected EOF
2016/04/11 19:18:11 Sending quit message and waiting for confirmation
2016/04/11 19:18:11 Shutting down - quit message received
2016/04/11 19:18:11 Closing channel for MessageID 1
2016/04/11 19:18:11 1: got response 0x0
2016/04/11 19:18:11 Closing network connection
2016/04/11 19:18:11 /connect/src/connect/auth/providers/ldap/client.go:143: (ldap) Failed to connect with TLS: LDAP Result Code 203 "": ldap: cannot process packet to add descriptions
2016/04/11 19:18:11 /connect/src/connect/auth/providers/ldap/ldap.go:180: (ldap) Unable to verify credentials: LDAP Result Code 203 "": ldap: cannot process packet to add descriptions
```

I'll have a PR opened with one solution for this shortly which will either defer a recover in the `getLDAPResultCode` function or check packet.Children for nil before checking length. But open to other approaches if anyone has any ideas.

### PR DESCRIPTION
**Pull request by trestletech**
nil packets have been observed when using StartTLS on a connection that
doesn't support it. These previously caused a panic but now will just
result in an unhelpful error.

Mimicking a similar strategy in https://github.com/go-ldap/ldap/blob/07a7330929b9ee80495c88a4439657d89c7dbd87/ldap.go#L89-L93

The nil packets on invalid StartTLS attempts should eventually be
corrected, but this makes the failure much more graceful.

Closes #58

### CODE REVIEW

File: error.go [hunk 1]
```diff
@@ -99,6 +99,12 @@ var LDAPResultCodeMap = map[uint8]string{
 }
 
 func getLDAPResultCode(packet *ber.Packet) (code uint8, description string) {
+	defer func() {
+		if r := recover(); r != nil {
+			code = ErrorUnexpectedResponse
+		}
+	}()
+
 	if len(packet.Children) >= 2 {
```
Comment (liggitt) [inline error.go]: I'd rather see a nil check on `packet`, and on `response` below

**Comment by trestletech** [comment]
Updated accordingly, @liggitt

**Comment by trestletech** [comment]
Hi @liggitt. Not trying to push, but curious if you had an ETA on this change. We're trying to decide if we should vendor our fork temporarily or wait for the merge.

Thanks again.

**Comment by liggitt** [comment]
sorry for the delay, go ahead and squash to a single commit for merge

**Comment by trestletech** [comment]
Thanks, @liggitt. Just force-pushed the squashed commit.

**Comment by liggitt** [comment]
thanks for the contribution
