### PR TITLE
Use Message Context

### LINKED ISSUE #68: Deadlock when LDAP server sends unexpected response packet
I have encountered an issue where a Bind Request to a particular LDAP server response with more than one response packet for the corresponding request messageID. The `Bind()` method only expects a single response which it reads and then returns (running a deferred `l.finishMessage(messageID)`).

In the meantime, the `processMessages()` goroutine is blocking on sending this unexpected extra response packet to the result channel for the Bind request, but the `Bind()` method never receives.

Going back to the deferred `l.finishMessage(messageID)`: The `Bind()` method wont return until this deferred call finishes but it is blocked on sending the `MessageFinish` message packet to the `processMessages()` goroutine which in turn is blocked because the `Bind()` method never receives from its channel. This is the deadlock.

It seems that this design for the `proccesMessages()` goroutine would, in general, always end up in deadlock if the server responds with more request packets than a request handler is expecting. This may be in violation of the protocol but I think that the client should be more resilient than this in handling a misbehaving server.

One solution that I've come up with is to make it so that calls to `finishMessage()` also signal to the `processMessages()` goroutine to stop blocking on an attempt to send a response packet for that message ID. Currently, the connection has a `chanResults` map which holds results channels which correspond to specific message IDs. We could replace this with a mapping of message IDs to context objects for that message. At the very least, this context would contain 2 items:

```go
type messageContext struct {
	done      chan struct{}
	responses chan *PacketResponse
}
```

The job of `finishMessage(messageID)` would change to acquiring a lock on this message context mapping, closing the `done` channel, then send the `MessageFinish` packet. In `processMessages()` we will have to change the `MessageResponse` handler to have a `select` statement which attempts to either send the response packet or receive from the `done` channel. If this `done` channel is closed it will not block and return instantly. The value is not important, but this signals that the request handler is done and we can abandon sending response packets to it.

### PR DESCRIPTION
**Pull request by jlhawn**
This patch introduces a new type called `messageContext` which is now the
return value of `(*Conn).sendMessage()`. The message context object still
contains a channel from which methods like, Add(), Bind(), Search(), etc.,
will receive response packets. It also has a field which holds the message
ID as well as a `done` channel which is used to prevent deadlock in the
`processMessages()` goroutine.

This is accomplished by also changing the `(*Conn).finishMessage()` method to
take a message context and close this `done` channel before sending a
`MessageFinish` packet to the `processMessages()` goroutine.

The `processMessages()` goroutine now has a `messageContexts` map which
replaces the `chanResults` map. Now, rather than sending response packets only
on the response channels, the `messageContext` has its own `sendResponse()`
method which uses a switch that blocks on sending a response packet *or*
waiting for its `done` channel to be closed by `finishMessage()`.

fixes #68

### CODE REVIEW

**Comment by jlhawn** [comment]
@liggitt PTAL

**Comment by liggitt** [comment]
Will look, thanks!

File: conn.go [hunk 1]
```diff
@@ -276,9 +293,11 @@ func (l *Conn) finishMessage(messageID int64) {
 	}
 	l.messageMutex.Unlock()
 
+	close(msgCtx.done)
```
Comment (liggitt) [inline conn.go]: shouldn't this happen before the the `isClosing` check? otherwise we may still have potential for deadlocks

File: conn.go [hunk 2]
```diff
@@ -362,26 +381,26 @@ func (l *Conn) processMessages() {
...
 				// All reads will return immediately
-				if chanResult, ok := l.chanResults[message.MessageID]; ok {
-					chanResult <- &PacketResponse{message.Packet, errors.New("ldap: connection timed out")}
+				if msgCtx, ok := l.messageContexts[message.MessageID]; ok {
 					l.Debug.Printf("Receiving message timeout for %d", message.MessageID)
-					delete(l.chanResults, message.MessageID)
-					close(chanResult)
+					msgCtx.sendResponse(&PacketResponse{message.Packet, errors.New("ldap: connection timed out")})
+					delete(l.messageContexts, message.MessageID)
+					close(msgCtx.responses)
```
Comment (liggitt) [inline conn.go]: I know this is preexisting, but `close`, then `delete`, as below

File: conn.go [hunk 3]
```diff
@@ -36,11 +36,27 @@ func (pr *PacketResponse) ReadPacket() (*ber.Packet, error) {
 	return pr.Packet, pr.Error
 }
 
+type messageContext struct {
+	id        int64
+	done      chan struct{}
+	responses chan *PacketResponse
+}
+
+func (msgCtx *messageContext) sendResponse(packet *PacketResponse) {
```
Comment (liggitt) [inline conn.go]: doc that this should only be done within the processMessages loop... we can't depend on the finishMessage-triggered `close(done)` taking effect before the processMessages-triggered `close(responses)` if this is called from a third goroutine, which would mean we'd have a ~50% chance of a panic trying to send a packet to a closed channel

**Comment by liggitt** [comment]
looks good, just a few comments. can you add a test that tries to trigger this as well (simulated request that returns multiple response packets when only one is expected)? ideally, it would fail without this patch in place (though the test might race with the finishRequest() message)

File: conn.go (hunk 2 above)
Comment (jlhawn) [inline conn.go]: updated below.

**Comment by jlhawn** [comment]
@liggitt Thanks for the quick review, I have updated the PR per your comments and added a new `TestConn` test case which fails on master but passes on this branch. I couldn't find any other tests that seem to simulate an LDAP server so I created a new type which I think you'll find very useful for other tests:

```go
// packetTranslatorConn is a helful type which can be used with various tests
// in this package. It implements the net.Conn interface to be used as an
// underlying connection for a *ldap.Conn. Most methods are no-ops but the
// Read() and Write() methods are able to translate ber-encoded packets for
// testing LDAP requests and responses.
//
// Test cases can simulate an LDAP server sending a response by calling the
// SendResponse() method with a ber-encoded LDAP response packet. Test cases
// can simulate an LDAP server receiving a request from a client by calling the
// ReceiveRequest() method which returns a ber-encoded LDAP request packet.
type packetTranslatorConn struct {
	sync.Mutex
	isClosed bool

	responseCond sync.Cond
	requestCond  sync.Cond

	responseBuf bytes.Buffer
	requestBuf  bytes.Buffer
}
```

You can use it in tests like this:

```go
func TestSomething(t *testing.T) {
	ptc := newPacketTranslatorConn()
	defer ptc.Close()

	conn := NewConn(ptc, false)
	conn.Start()
	defer conn.Close()

	// Create an LDAP request packet and send it as usual.
	requestPacket := makeRequestPacket()
	msgCtx, _ := conn.sendMessage()

	// Decode the request packet on the other side of the connection.
	serverRequest, _ := ptc.ReceiveRequest()

	// Create a response packet and send it.
	serverResponse := makeResponsePacket()
	ptc.SendResponse(serverResponse)

	// Handle the response as usual.
	responsePacket <- msgCtx.responses
}
```

File: conn_test.go [hunk 4]
```diff
@@ -51,3 +56,271 @@ func TestUnresponsiveConnection(t *testing.T) {
...
+func testSendRequest(t *testing.T, ptc *packetTranslatorConn, conn *Conn) *messageContext {
+	requestPacket := ber.Encode(ber.ClassUniversal, ber.TypeConstructed, ber.TagSequence, nil, "LDAP Request")
+	requestPacket.AppendChild(ber.NewInteger(ber.ClassUniversal, ber.TypePrimitive, ber.TagInteger, conn.nextMessageID(), "MessageID"))
+
+	var (
+		msgCtx *messageContext
+		err    error
+	)
+
+	runWithTimeout(t, time.Millisecond, func() {
```
Comment (liggitt) [inline conn_test.go]: millisecond timing is way too tight for something depending on a loop inside a separate goroutine... can lead to test flake failures if anything else is hitting the CPU while the test is running. If the main purpose is to prevent a test hanging forever, I'd do something like a second

File: conn_test.go [hunk 5]
```diff
@@ -51,3 +56,271 @@ func TestUnresponsiveConnection(t *testing.T) {
...
+	done := make(chan struct{})
+	go func() {
+		f()
+		close(done)
+	}()
+
+	select {
+	case <-done: // Success!
+	case <-time.After(timeout):
+		t.Fatal("timed out")
```
Comment (liggitt) [inline conn_test.go]: fataling inside a helper func makes it hard to see the point in the main test func that failed. include the relevant caller info like this:

```
_, file, line, _ := runtime.Caller(1)
t.Fatalf("%s:%s: timed out", file, line)
```

File: conn_test.go [hunk 6]
```diff
@@ -51,3 +56,271 @@ func TestUnresponsiveConnection(t *testing.T) {
...
+// underlying connection for a *ldap.Conn. Most methods are no-ops but the
+// Read() and Write() methods are able to translate ber-encoded packets for
+// testing LDAP requests and responses.
+//
+// Test cases can simulate an LDAP server sending a response by calling the
+// SendResponse() method with a ber-encoded LDAP response packet. Test cases
+// can simulate an LDAP server receiving a request from a client by calling the
+// ReceiveRequest() method which returns a ber-encoded LDAP request packet.
+type packetTranslatorConn struct {
+	sync.Mutex
```
Comment (liggitt) [inline conn_test.go]: don't inline this... holders of the test conn struct probably shouldn't see it as a lockable object

**Comment by jlhawn** [comment]
@liggitt thanks for the comments. I've updated the branch again.

> added a new `TestConn` test case which fails on master but passes on this branch.

I forgot to mention that the new test doesn't build on master without a few modifications.

File: conn.go [hunk 7]
```diff
@@ -253,18 +267,25 @@ func (l *Conn) sendMessageWithFlags(packet *ber.Packet, flags sendMessageFlags)
...
+		},
 	}
 	l.sendProcessMessage(message)
-	return out, nil
+	return message.Context, nil
 }
 
-func (l *Conn) finishMessage(messageID int64) {
+func (l *Conn) finishMessage(msgCtx *messageContext) {
+	close(msgCtx.done)
```
Comment (jlhawn) [inline conn.go]: The best way to see the new tests fail is to just comment out this line.

File: conn.go [hunk 8]
```diff
@@ -36,11 +36,29 @@ func (pr *PacketResponse) ReadPacket() (*ber.Packet, error) {
 	return pr.Packet, pr.Error
 }
 
+type messageContext struct {
+	id        int64
+	done      chan struct{}
```
Comment (liggitt) [inline conn.go]: can you add godoc saying this should only be closed from `finishMessage`

File: conn.go [hunk 9]
```diff
@@ -36,11 +36,29 @@ func (pr *PacketResponse) ReadPacket() (*ber.Packet, error) {
...
+	responses chan *PacketResponse
```
Comment (liggitt) [inline conn.go]: and this should only be closed from `processMessages`, and only sent to from `sendResponse`

**Comment by liggitt** [comment]
thanks for the report and fix
