### PR TITLE
Fix request timeout handling

### LINKED ISSUE #387: Go routine leak at https://github.com/go-ldap/ldap/blob/master/conn.go#L498
Thousands of goroutines kept waiting on sleep as a result of search operation with request timeout.

In the below go routine dump we see 16714 routines are waiting.

`16714 @ 0x844916 0x87168e 0xf49475 0x874801

0x87168d	time.Sleep+0x12d						/usr/lib/golang/src/runtime/time.go:193

0xf49474	github.com/go-ldap/ldap/v3.(*Conn).processMessages.func2+0x54	/workdir/.build/golib/pkg/mod/github.com/go-ldap/ldap/v3@v3.4.2/conn.go:498`

it seems like those functions will complete when the timeout expires and then the goroutine would go away.
Should we be using a select so they can stop the sleep if the response has already been received

### PR DESCRIPTION
**Pull request by cpuschma**
Fixes #387

### CODE REVIEW

File: conn.go [hunk 1]
```diff
@@ -87,7 +87,7 @@ const (
 type Conn struct {
 	// requestTimeout is loaded atomically
 	// so we need to ensure 64-bit alignment on 32-bit platforms.
-	requestTimeout      int64
+	requestTimeout      time.Duration
```
Comment (johnweldon) [inline conn.go:90]: If we're no-longer loading requestTimeout atomically, we can probably remove the comment.

Has it been established that we don't need to read/write this field atomically? (I'm curious why it was set up that way before)

**Review by johnweldon — APPROVED** [review]
Assuming it's okay to remove the atomic access, LGTM

File: conn.go (hunk 1 above)
Comment (cpuschma) [reply conn.go:90]: I overlooked the comment, thanks for pointing out! Looking at the commit history, this was added in 412981c9 by Psychotropos. After reading through the comments of PR #199  and the linked issues this still seems to be a problem for the supported Go versions. I'll revert this part and stick with int64 and atomic loading to ensure 64-bit alignment. 

I thought I can get rid of the "unnecessary" type conversion 😅

**Comment by cpuschma** [comment]
@johnweldon Maybe it's time to create a new tag and release? There have been a few changes since the last release: 
* Update test matrix to Go v1.14+
* Support for configurable logger
* Linter cleanup
* Update minimum required Go version to 1.14
* Allow NTLM authentication without a password
* Add missing Client interface methods
* Implement Subtree delete control type
* feat: return referrals for modify operation
* Add Entry Unmarshal
* added int and []byte type to entry unmarshal
* Update dependencies to satisfy new ntlmssp.ProcessChallenge signature
* Add String() methods to DN and its subtypes
* Fix request timeout handling
