### PR TITLE
feat: Refactor `ParseDN` function to fix resource usage and invalid parsings (fixes #487)

### LINKED ISSUE #487: Memory leak
The following snippet causes unexpectedly high memory usage:

```go
func BenchmarkParseSubject(b *testing.B) {
	for n := 0; n < b.N; n++ {
		_, err := ParseSubjectStringToRawDERBytes("DF=#6666666666665006838820013100000746939546349182108463491821809FBFFFFFFFFF")
		if err == nil {
			b.Fatal("expected error, but got none")
		}
	}
}
```

Run with:

```console
go test -bench=. -benchmem ./pkg/util/pki/...
```

Before this change:

```text
goos: darwin
goarch: arm64
pkg: github.com/cert-manager/cert-manager/pkg/util/pki
BenchmarkParseSubject-12              58          20398892 ns/op        1665740367 B/op       58 allocs/op
```

### PR DESCRIPTION
**Pull request by cpuschma**
This PR reworks the `ParseDN` function, which has been very resource consuming for reading one byte at a time and couldn't handle certain characters. This implementation is based upon inteons PR for cert-manager, which wasn't fully compatible with the RFC 4514.

This PR also:
* Moves an unexported variable to a function scoped constant to free up the name `hex`
* Renames the imported package `enchex` to it's original name `hex` for better readabilty
* Improves the readability of `ParseDN` test failures

If this resolves the reported problems, we can revert #466.

### CODE REVIEW

**Comment by cpuschma** [comment]
Additionally, results of some benchmarking benchmark:

**Summary**
```
goos: linux
goarch: amd64
pkg: github.com/go-ldap/ldap
cpu: AMD Ryzen 5 5600X 6-Core Processor             
                │   old.txt    │               new.txt               │
                │    sec/op    │   sec/op     vs base                │
ParseSubject-12   2392.0n ± 1%   754.2n ± 1%  -68.47% (p=0.000 n=15)

                │   old.txt   │              new.txt               │
                │    B/op     │    B/op     vs base                │
ParseSubject-12   1865.0 ± 0%   408.0 ± 0%  -78.12% (p=0.000 n=15)

                │  old.txt   │              new.txt               │
                │ allocs/op  │ allocs/op   vs base                │
ParseSubject-12   58.00 ± 0%   10.00 ± 0%  -82.76% (p=0.000 n=15)
```

**Old implementation:**
```
BenchmarkParseSubject-12    	  673922	      2258 ns/op	    1865 B/op	      58 allocs/op
BenchmarkParseSubject-12    	  519794	      2403 ns/op	    1865 B/op	      58 allocs/op
BenchmarkParseSubject-12    	  458138	      2411 ns/op	    1865 B/op	      58 allocs/op
BenchmarkParseSubject-12    	  426906	      2440 ns/op	    1865 B/op	      58 allocs/op
BenchmarkParseSubject-12    	  502710	      2369 ns/op	    1865 B/op	      58 allocs/op
```
**New implementation:**:
```
BenchmarkParseSubject-12    	 1606474	       773.1 ns/op	     408 B/op	      10 allocs/op
BenchmarkParseSubject-12    	 1554079	       768.1 ns/op	     408 B/op	      10 allocs/op
BenchmarkParseSubject-12    	 1594885	       760.0 ns/op	     408 B/op	      10 allocs/op
BenchmarkParseSubject-12    	 1564299	       754.2 ns/op	     408 B/op	      10 allocs/op
BenchmarkParseSubject-12    	 1547341	       755.9 ns/op	     408 B/op	      10 allocs/op
```

File: dn.go [hunk 1]
```diff
@@ -108,114 +142,154 @@ func (d *DN) String() string {
 	return strings.Join(rdns, ",")
 }
 
+// Remove leading and trailing spaces from the attribute type and value
+// and unescape any escaped characters in these fields
+// Remove leading and trailing spaces from the attribute type and value
+// and unescape any escaped characters in these fields
```
Comment (johnweldon) [inline dn.go:148]: Accidentally doubled the comment?

File: v3/dn.go [hunk 2]
```diff
@@ -108,114 +142,154 @@ func (d *DN) String() string {
 	return strings.Join(rdns, ",")
 }
 
+// Remove leading and trailing spaces from the attribute type and value
+// and unescape any escaped characters in these fields
+// Remove leading and trailing spaces from the attribute type and value
+// and unescape any escaped characters in these fields
```
Comment (johnweldon) [inline v3/dn.go:148]: ditto

**Review by johnweldon — APPROVED** [review]
LGTM, except for the comment typo

File: dn.go (hunk 1 above)
Comment (cpuschma) [reply dn.go]: Thank you for pointing this out @johnweldon ❤️

File: dn.go [hunk 3]
```diff
@@ -108,114 +142,152 @@ func (d *DN) String() string {
...
+}
+
+func decodeEncodedString(str string) (string, error) {
+	decoded, err := hex.DecodeString(str)
+	if err != nil {
+		return "", fmt.Errorf("failed to decode BER encoding: %s", err)
+	}
+
+	var rawValue asn1.RawValue
+	result, err := asn1.Unmarshal(decoded, &rawValue)
```
Comment (inteon) [inline dn.go:222]: @cpuschma @johnweldon 
Great to see you are improving this function!
There is one small issue with this approach that I also figured out too late: `asn1.Unmarshal(` only supports DER parsing, while the `github.com/go-asn1-ber/asn1-ber` library supports BER parsing too.
This means that parseDN deviates from the RFC, possibly resulting in unexpected limitations for the user.

Comment (cpuschma) [reply dn.go:222]: I'll look into this and extend the test cases. We didn't catch on that either. Thank you for pointing this out, @inteon!

Comment (inteon) [reply dn.go:222]: I also have some extra testcases that might be useful. Will create a PR soon.
